<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { Share2, Scissors, ExternalLink, Loader2, Download, ChevronDown, Check } from 'lucide-vue-next';
import { useAuth } from '../services/auth';

const { getAuthHeaders } = useAuth();
const API_BASE = import.meta.env.VITE_API_URL;

const props = defineProps<{
  videoId: string;
  videoTitle: string;
  videoUrl: string;
  takeaways: any[];
  mindmapRaw: string | null;
}>();

const isExportingToNotion = ref(false);

const copyToClipboard = (text: string, msg: string, title: string = '已复制到剪贴板') => {
  console.log('Attempting to copy text to clipboard...');

  const handleSuccess = () => {
    console.log('Copy success!');
    window.dispatchEvent(new CustomEvent('notify', {
      detail: {
        message: msg,
        title: title,
        type: 'success',
        duration: 5000 // 5秒自动关闭
      }
    }));
  };

  const handleError = (err: any) => {
    console.error('Copy failed:', err);
    window.dispatchEvent(new CustomEvent('notify', {
      detail: {
        message: '剪贴板访问失败，请手动选择复制',
        title: '复制失败',
        type: 'error',
        duration: 5000
      }
    }));
  };

  // Modern API
  if (navigator.clipboard && window.isSecureContext) {
    navigator.clipboard.writeText(text).then(handleSuccess).catch(handleError);
  } else {
    // Fallback for non-secure context or older browsers
    try {
      const textArea = document.createElement('textarea');
      textArea.value = text;
      textArea.style.position = 'fixed';
      textArea.style.left = '-9999px';
      textArea.style.top = '0';
      document.body.appendChild(textArea);
      textArea.focus();
      textArea.select();
      const successful = document.execCommand('copy');
      document.body.removeChild(textArea);
      if (successful) {
        handleSuccess();
      } else {
        handleError('execCommand returned false');
      }
    } catch (err) {
      handleError(err);
    }
  }
};

const formatTimeFromSeconds = (seconds: number) => {
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  return `${m}:${s.toString().padStart(2, '0')}`;
};

const exportAsMarkdown = () => {
  if (!props.takeaways.length) return;

  let md = `# ${props.videoTitle || '视频学习笔记'}\n\n`;
  md += `> 📺 视频来源: [点击播放](${props.videoUrl})\n`;
  md += `> 📅 分析日期: ${new Date().toLocaleDateString()}\n\n`;

  md += `## 🤖 AI 核心摘要\n\n`;
  props.takeaways.forEach((t, i) => {
    const ts = formatTimeFromSeconds(t.timestamp);
    md += `### ${i + 1}. [${ts}] ${t.title}\n`;
    md += `${t.summary}\n\n`;
  });

  if (props.mindmapRaw) {
    // 转换为 Mermaid 流程图语法 (graph LR)，使用箭头指示逻辑流向
    // Convert to Mermaid flowchart (graph LR) with explicit arrows
    const lines = props.mindmapRaw.split('\n');
    const connections: string[] = [];
    const lastNodesByLevel: string[] = [];

    lines.forEach((line, index) => {
      const match = line.match(/^(#+)\s+(.*)$/);
      if (match) {
        const level = match[1].length;
        const rawText = match[2].trim().replace(/[()\[\]{}]/g, '').replace(/"/g, "'");
        const nodeId = `n${index}`;

        // 根据层级应用样式类 (Apply styles by level)
        let styleClass = '';
        if (level === 1) styleClass = ':::root';
        else if (level === 2) styleClass = ':::branch';
        else styleClass = ':::leaf';

        // 根据层级给节点加上不同的形状
        let nodeDef = '';
        if (level === 1) {
          nodeDef = `${nodeId}(("${rawText}"))${styleClass}`;
        } else if (level === 2) {
          nodeDef = `${nodeId}("${rawText}")${styleClass}`;
        } else {
          nodeDef = `${nodeId}["${rawText}"]${styleClass}`;
        }

        if (level > 1) {
          const parentId = lastNodesByLevel[level - 2];
          if (parentId) {
            connections.push(`${parentId} --> ${nodeDef}`);
          } else {
            connections.push(nodeDef);
          }
        } else {
          connections.push(nodeDef);
        }
        lastNodesByLevel[level - 1] = nodeId;
      }
    });

    const styleDefs = [
      '  classDef root fill:#6366f1,stroke:#4338ca,stroke-width:2px,color:#fff,font-weight:bold',
      '  classDef branch fill:#e0e7ff,stroke:#6366f1,stroke-width:1.5px,color:#1e1b4b',
      '  classDef leaf fill:#f8fafc,stroke:#cbd5e1,stroke-width:1px,color:#334155'
    ].join('\n');

    md += `## 🧠 知识流向图 (Mermaid Flowchart)\n\n`;
    md += `\`\`\`mermaid\ngraph LR\n${styleDefs}\n${connections.join('\n')}\n\`\`\`\n\n`;
    md += `---\n*Generated by AI Video Highlights*`;
  }
  copyToClipboard(md, 'Markdown 笔记已准备好，去 Notion/Obsidian 粘贴吧！', 'Markdown 导出成功');
};

const exportToNotion = async () => {
  if (isExportingToNotion.value) return;

  isExportingToNotion.value = true;
  try {
    const response = await fetch(`${API_BASE}/api/videos/${props.videoId}/export/notion`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        ...getAuthHeaders()
      },
      body: JSON.stringify({})
    });

    const result = await response.json();

    if (result.success) {
      window.dispatchEvent(new CustomEvent('notify', {
        detail: {
          message: '已成功导出到 Notion！',
          title: '导出成功',
          type: 'success',
          duration: 5000
        }
      }));
      // Optional: Open Notion page
      if (result.url) {
        window.open(result.url, '_blank');
      }
    } else {
      throw new Error(result.message || '导出失败');
    }
  } catch (error: any) {
    console.error('Notion export error:', error);
    window.dispatchEvent(new CustomEvent('notify', {
      detail: {
        message: error.message || '请确保后端已配置 NOTION_API_KEY',
        title: '导出失败',
        type: 'error',
        duration: 5000
      }
    }));
  } finally {
    isExportingToNotion.value = false;
  }
};

const generateEditingScript = () => {
  if (!props.takeaways.length) return;

  let script = `# 🎬 视频剪辑脚本建议\n\n`;
  script += `## ✂️ FFMPEG 提取指令 (快速剪辑)\n\n`;

  props.takeaways.forEach((t, i) => {
    const start = t.timestamp;
    // 估算结束时间：要么是下一条开始，要么是加 20s
    const nextStart = props.takeaways[i+1]?.timestamp || (start + 20);
    const duration = nextStart - start;

    script += `### 片段 ${i+1}: ${t.title}\n`;
    script += `\`\`\`bash\nffmpeg -ss ${start} -t ${duration} -i input_video.mp4 -c copy clip_${i+1}.mp4\n\`\`\`\n\n`;
  });

  script += `\n## 📝 旁白/叙文建议\n\n`;
  script += props.takeaways.map((t, i) => `【片段${i+1}】展现：${t.title}。建议文案：${t.summary}`).join('\n\n');

  copyToClipboard(script, '剪辑脚本与 FFMPEG 指令已生成！', '剪辑脚本生成成功');
};
const isDownloading = ref(false);
const downloadQuality = ref('1080');

const downloadFullVideo = async () => {
  if (isDownloading.value) return;

  isDownloading.value = true;
  try {
    const response = await fetch(`${API_BASE}/api/videos/${props.videoId}/download?quality=${downloadQuality.value}`, {
      method: 'GET',
      headers: getAuthHeaders()
    });

    if (!response.ok) {
      let message = '下载失败';
      const contentType = response.headers.get('content-type') || '';

      if (contentType.includes('application/json')) {
        const err = await response.json();
        message = err.message || err.error || message;
      } else {
        const text = await response.text();
        if (text) {
          message = text;
        }
      }

      throw new Error(message);
    }

    const blob = await response.blob();
    const downloadUrl = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = downloadUrl;
    link.download = `${props.videoTitle.slice(0, 30)}_full.mp4`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(downloadUrl);

    window.dispatchEvent(new CustomEvent('notify', {
      detail: {
        message: '视频下载已开始',
        title: '下载成功',
        type: 'success',
        duration: 3000
      }
    }));
  } catch (error: any) {
    console.error('Download error:', error);
    window.dispatchEvent(new CustomEvent('notify', {
      detail: {
        message: error.message || '视频下载失败，请稍后重试',
        title: '下载失败',
        type: 'error',
        duration: 5000
      }
    }));
  } finally {
    isDownloading.value = false;
  }
};
const showQualityMenu = ref(false);
const showShareMenu = ref(false);
const qualityOptions = [
  { label: '1080P', value: '1080' },
  { label: '2K', value: '1440' },
  { label: '4K', value: '2160' },
  { label: '原画', value: 'best' }
];

const selectQuality = (val: string) => {
  downloadQuality.value = val;
  showQualityMenu.value = false;
};

const getQualityLabel = (val: string) => {
  return qualityOptions.find(opt => opt.value === val)?.label || val;
};

const toggleShareMenu = (e: MouseEvent) => {
  e.stopPropagation();
  showShareMenu.value = !showShareMenu.value;
  showQualityMenu.value = false;
};

const toggleQualityMenu = (e: MouseEvent) => {
  e.stopPropagation();
  showQualityMenu.value = !showQualityMenu.value;
  showShareMenu.value = false;
};

// 点击外部关闭
onMounted(() => {
  window.addEventListener('click', () => {
    showShareMenu.value = false;
    showQualityMenu.value = false;
  });
  
  window.addEventListener('resize', () => {
    showShareMenu.value = false;
    showQualityMenu.value = false;
  });
});
</script>

<template>
  <div class="export-actions">
    <!-- 1. 核心导出菜单 (Notion & Markdown & Script) -->
    <div class="dropdown-wrapper" :class="{ 'is-open': showShareMenu }">
      <button class="btn-action-primary" @click.stop="toggleShareMenu">
        <Share2 :size="14" />
        <span>同步/分享</span>
      </button>
      <div v-if="showShareMenu" class="dropdown-menu">
        <div class="dropdown-item" @click="exportToNotion" :class="{ disabled: !takeaways.length || isExportingToNotion }">
          <Loader2 v-if="isExportingToNotion" :size="14" class="spin" />
          <ExternalLink v-else :size="14" />
          <div class="item-text">
            <span>导出到 Notion</span>
            <small>同步到您的知识库</small>
          </div>
        </div>
        <div class="dropdown-divider"></div>
        <div class="dropdown-item" @click="exportAsMarkdown" :class="{ disabled: !takeaways.length }">
          <Share2 :size="14" />
          <div class="item-text">
            <span>复制 Markdown</span>
            <small>兼容 Obsidian/Logseq</small>
          </div>
        </div>
        <div class="dropdown-item" @click="generateEditingScript" :class="{ disabled: !takeaways.length }">
          <Scissors :size="14" />
          <div class="item-text">
            <span>生成剪辑脚本</span>
            <small>复制指令与分段建议</small>
          </div>
        </div>
      </div>
    </div>

    <!-- 2. 精简版下载组件 -->
    <div class="download-cluster">
      <div class="quality-selector" @click.stop="toggleQualityMenu">
        <span class="current-quality">{{ getQualityLabel(downloadQuality) }}</span>
        <ChevronDown :size="12" class="chevron-icon" :class="{ 'rotate': showQualityMenu }" />
        
        <!-- 自定义模拟下拉菜单 -->
        <div v-if="showQualityMenu" class="quality-dropdown-menu">
          <div 
            v-for="opt in qualityOptions" 
            :key="opt.value"
            class="quality-option"
            :class="{ 'active': downloadQuality === opt.value }"
            @click.stop="selectQuality(opt.value)"
          >
            <span>{{ opt.label }}</span>
            <Check v-if="downloadQuality === opt.value" :size="12" class="check-icon" />
          </div>
        </div>
      </div>
      <button 
        class="btn-download-trigger" 
        @click="downloadFullVideo" 
        :disabled="isDownloading"
        title="下载完整视频"
      >
        <Loader2 v-if="isDownloading" :size="14" class="spin" />
        <Download v-else :size="14" />
        <span>下载</span>
      </button>
    </div>
  </div>
</template>

<style scoped>
.export-actions {
  display: flex;
  align-items: center;
  gap: 8px;
}

/* 导出下拉按钮 (Dropdown) */
.dropdown-wrapper {
  position: relative;
}

.btn-action-primary {
  display: flex;
  align-items: center;
  gap: 6px;
  background: rgba(255, 255, 255, 0.05);
  border: 1px solid rgba(255, 255, 255, 0.1);
  color: var(--text-secondary);
  border-radius: 8px;
  padding: 0 12px;
  height: 32px;
  font-size: 0.75rem;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.2s cubic-bezier(0.4, 0, 0.2, 1);
  white-space: nowrap;
  flex-shrink: 0;
}

.btn-action-primary:hover {
  background: rgba(255, 255, 255, 0.1);
  border-color: rgba(255, 255, 255, 0.2);
  color: #fff;
  transform: translateY(-1px);
}

.dropdown-menu {
  position: absolute;
  top: calc(100% + 12px); /* 稍微拉开间距更显精致 */
  right: 0;
  width: 180px;
  background: #1e293b;
  border: 1px solid rgba(255, 255, 255, 0.15); /* 再次增强边框对比 */
  border-radius: 12px;
  box-shadow: 0 20px 40px rgba(0, 0, 0, 0.7); /* 更深邃的长投影 */
  padding: 6px;
  z-index: 9999; /* 保证绝对领先的层级 */
  animation: dropdownIn 0.2s cubic-bezier(0.4, 0, 0.2, 1);
}

/* 移除了 drop-up 相关样式，锁定向下弹出 */

/* 移除原有的 Hover 触发逻辑，改为点击由 v-if 控制 */
/* .dropdown-wrapper:hover .dropdown-menu {
  opacity: 1;
  visibility: visible;
  transform: translateY(0);
} */

.dropdown-item {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 8px 10px;
  border-radius: 8px;
  color: var(--text-secondary);
  cursor: pointer;
  transition: all 0.2s;
}

.dropdown-item:hover:not(.disabled) {
  background: rgba(255, 255, 255, 0.05);
  color: #fff;
}

.dropdown-item.disabled {
  opacity: 0.4;
  cursor: not-allowed;
}

.item-text {
  display: flex;
  flex-direction: column;
}

.item-text span {
  font-size: 0.75rem;
  font-weight: 600;
}

.item-text small {
  font-size: 0.6rem;
  opacity: 0.6;
}

.dropdown-divider {
  height: 1px;
  background: rgba(255, 255, 255, 0.05);
  margin: 4px 6px;
}

/* 下载合拢组件 (Download Cluster) */
.download-cluster {
  display: flex;
  align-items: stretch;
  background: rgba(255, 255, 255, 0.05);
  border: 1px solid rgba(255, 255, 255, 0.1);
  border-radius: 8px;
  /* 移除 overflow: hidden，允许自定义下拉菜单弹出 */
  height: 32px;
  transition: all 0.2s ease;
  position: relative;
}

.download-cluster:hover:not(:has(.btn-download-trigger:disabled)) {
  border-color: rgba(255, 255, 255, 0.2);
  background: rgba(255, 255, 255, 0.1);
  transform: translateY(-1px);
}

.quality-selector {
  border-right: 1px solid rgba(255, 255, 255, 0.1);
  display: flex;
  align-items: center;
  padding: 0 8px;
  cursor: pointer;
  position: relative; /* 核心：确保下拉框相对于此定位 */
  user-select: none;
  min-width: 65px;
  justify-content: space-between;
  gap: 4px;
}

.current-quality {
  color: var(--text-secondary);
  font-size: 0.65rem;
  font-weight: 700;
  font-family: 'JetBrains Mono', monospace;
}

.chevron-icon {
  opacity: 0.5;
  transition: transform 0.2s ease;
}

.chevron-icon.rotate {
  transform: rotate(180deg);
}

.quality-dropdown-menu {
  position: absolute;
  top: calc(100% + 12px);
  right: 0; /* 改为右对齐 */
  width: 110px;
  background: #1e293b;
  border: 1px solid rgba(255, 255, 255, 0.15);
  border-radius: 10px;
  box-shadow: 0 20px 40px rgba(0, 0, 0, 0.7);
  padding: 5px;
  z-index: 9999;
  animation: dropdownIn 0.2s cubic-bezier(0.4, 0, 0.2, 1);
}

@keyframes dropdownIn {
  from { opacity: 0; transform: translateY(-12px); }
  to { opacity: 1; transform: translateY(0); }
}

.quality-option {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 8px 10px;
  border-radius: 6px;
  color: var(--text-secondary);
  font-size: 0.72rem;
  transition: all 0.2s;
  font-weight: 500;
}

.quality-option:hover {
  background: rgba(255, 255, 255, 0.05);
  color: #fff;
}

.quality-option.active {
  background: rgba(99, 102, 241, 0.1);
  color: var(--accent-color);
}

.check-icon {
  color: var(--accent-color);
}

.btn-download-trigger {
  background: transparent;
  border: none;
  color: var(--text-secondary);
  display: flex;
  align-items: center;
  gap: 4px;
  padding: 0 10px;
  font-size: 0.72rem;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.2s;
  white-space: nowrap;
  flex-shrink: 0;
}

.btn-download-trigger:hover:not(:disabled) {
  color: #fff;
  background: rgba(255, 255, 255, 0.05);
}

.btn-download-trigger:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}
</style>
