<script setup lang="ts">
import { ref } from 'vue';
import { Share2, Scissors, ExternalLink, Loader2, Download } from 'lucide-vue-next';
import { useAuth } from '../services/auth';

const { getAuthHeaders } = useAuth();
const API_BASE = import.meta.env.VITE_API_URL;

const props = defineProps<{
  videoId: string;
  videoTitle: string;
  videoUrl: string;
  takeaways: any[];
  mindmapRaw: string | null;
}>();

const isExportingToNotion = ref(false);

const copyToClipboard = (text: string, msg: string, title: string = '已复制到剪贴板') => {
  console.log('Attempting to copy text to clipboard...');

  const handleSuccess = () => {
    console.log('Copy success!');
    window.dispatchEvent(new CustomEvent('notify', {
      detail: {
        message: msg,
        title: title,
        type: 'success',
        duration: 5000 // 5秒自动关闭
      }
    }));
  };

  const handleError = (err: any) => {
    console.error('Copy failed:', err);
    window.dispatchEvent(new CustomEvent('notify', {
      detail: {
        message: '剪贴板访问失败，请手动选择复制',
        title: '复制失败',
        type: 'error',
        duration: 5000
      }
    }));
  };

  // Modern API
  if (navigator.clipboard && window.isSecureContext) {
    navigator.clipboard.writeText(text).then(handleSuccess).catch(handleError);
  } else {
    // Fallback for non-secure context or older browsers
    try {
      const textArea = document.createElement('textarea');
      textArea.value = text;
      textArea.style.position = 'fixed';
      textArea.style.left = '-9999px';
      textArea.style.top = '0';
      document.body.appendChild(textArea);
      textArea.focus();
      textArea.select();
      const successful = document.execCommand('copy');
      document.body.removeChild(textArea);
      if (successful) {
        handleSuccess();
      } else {
        handleError('execCommand returned false');
      }
    } catch (err) {
      handleError(err);
    }
  }
};

const formatTimeFromSeconds = (seconds: number) => {
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  return `${m}:${s.toString().padStart(2, '0')}`;
};

const exportAsMarkdown = () => {
  if (!props.takeaways.length) return;

  let md = `# ${props.videoTitle || '视频学习笔记'}\n\n`;
  md += `> 📺 视频来源: [点击播放](${props.videoUrl})\n`;
  md += `> 📅 分析日期: ${new Date().toLocaleDateString()}\n\n`;

  md += `## 🤖 AI 核心摘要\n\n`;
  props.takeaways.forEach((t, i) => {
    const ts = formatTimeFromSeconds(t.timestamp);
    md += `### ${i + 1}. [${ts}] ${t.title}\n`;
    md += `${t.summary}\n\n`;
  });

  if (props.mindmapRaw) {
    // 转换为 Mermaid 流程图语法 (graph LR)，使用箭头指示逻辑流向
    // Convert to Mermaid flowchart (graph LR) with explicit arrows
    const lines = props.mindmapRaw.split('\n');
    const connections: string[] = [];
    const lastNodesByLevel: string[] = [];

    lines.forEach((line, index) => {
      const match = line.match(/^(#+)\s+(.*)$/);
      if (match) {
        const level = match[1].length;
        const rawText = match[2].trim().replace(/[()\[\]{}]/g, '').replace(/"/g, "'");
        const nodeId = `n${index}`;

        // 根据层级应用样式类 (Apply styles by level)
        let styleClass = '';
        if (level === 1) styleClass = ':::root';
        else if (level === 2) styleClass = ':::branch';
        else styleClass = ':::leaf';

        // 根据层级给节点加上不同的形状
        let nodeDef = '';
        if (level === 1) {
          nodeDef = `${nodeId}(("${rawText}"))${styleClass}`;
        } else if (level === 2) {
          nodeDef = `${nodeId}("${rawText}")${styleClass}`;
        } else {
          nodeDef = `${nodeId}["${rawText}"]${styleClass}`;
        }

        if (level > 1) {
          const parentId = lastNodesByLevel[level - 2];
          if (parentId) {
            connections.push(`${parentId} --> ${nodeDef}`);
          } else {
            connections.push(nodeDef);
          }
        } else {
          connections.push(nodeDef);
        }
        lastNodesByLevel[level - 1] = nodeId;
      }
    });

    const styleDefs = [
      '  classDef root fill:#6366f1,stroke:#4338ca,stroke-width:2px,color:#fff,font-weight:bold',
      '  classDef branch fill:#e0e7ff,stroke:#6366f1,stroke-width:1.5px,color:#1e1b4b',
      '  classDef leaf fill:#f8fafc,stroke:#cbd5e1,stroke-width:1px,color:#334155'
    ].join('\n');

    md += `## 🧠 知识流向图 (Mermaid Flowchart)\n\n`;
    md += `\`\`\`mermaid\ngraph LR\n${styleDefs}\n${connections.join('\n')}\n\`\`\`\n\n`;
    md += `---\n*Generated by AI Video Highlights*`;
  }
  copyToClipboard(md, 'Markdown 笔记已准备好，去 Notion/Obsidian 粘贴吧！', 'Markdown 导出成功');
};

const exportToNotion = async () => {
  if (isExportingToNotion.value) return;

  isExportingToNotion.value = true;
  try {
    const response = await fetch(`${API_BASE}/api/videos/${props.videoId}/export/notion`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        ...getAuthHeaders()
      },
      body: JSON.stringify({})
    });

    const result = await response.json();

    if (result.success) {
      window.dispatchEvent(new CustomEvent('notify', {
        detail: {
          message: '已成功导出到 Notion！',
          title: '导出成功',
          type: 'success',
          duration: 5000
        }
      }));
      // Optional: Open Notion page
      if (result.url) {
        window.open(result.url, '_blank');
      }
    } else {
      throw new Error(result.message || '导出失败');
    }
  } catch (error: any) {
    console.error('Notion export error:', error);
    window.dispatchEvent(new CustomEvent('notify', {
      detail: {
        message: error.message || '请确保后端已配置 NOTION_API_KEY',
        title: '导出失败',
        type: 'error',
        duration: 5000
      }
    }));
  } finally {
    isExportingToNotion.value = false;
  }
};

const generateEditingScript = () => {
  if (!props.takeaways.length) return;

  let script = `# 🎬 视频剪辑脚本建议\n\n`;
  script += `## ✂️ FFMPEG 提取指令 (快速剪辑)\n\n`;

  props.takeaways.forEach((t, i) => {
    const start = t.timestamp;
    // 估算结束时间：要么是下一条开始，要么是加 20s
    const nextStart = props.takeaways[i+1]?.timestamp || (start + 20);
    const duration = nextStart - start;

    script += `### 片段 ${i+1}: ${t.title}\n`;
    script += `\`\`\`bash\nffmpeg -ss ${start} -t ${duration} -i input_video.mp4 -c copy clip_${i+1}.mp4\n\`\`\`\n\n`;
  });

  script += `\n## 📝 旁白/叙文建议\n\n`;
  script += props.takeaways.map((t, i) => `【片段${i+1}】展现：${t.title}。建议文案：${t.summary}`).join('\n\n');

  copyToClipboard(script, '剪辑脚本与 FFMPEG 指令已生成！', '剪辑脚本生成成功');
};
const isDownloading = ref(false);

const downloadFullVideo = async () => {
  if (isDownloading.value) return;

  isDownloading.value = true;
  try {
    const response = await fetch(`${API_BASE}/api/videos/${props.videoId}/download`, {
      method: 'GET',
      headers: getAuthHeaders()
    });

    if (!response.ok) {
      const err = await response.json();
      throw new Error(err.message || '下载失败');
    }

    const blob = await response.blob();
    const downloadUrl = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = downloadUrl;
    link.download = `${props.videoTitle.slice(0, 30)}_full.mp4`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(downloadUrl);

    window.dispatchEvent(new CustomEvent('notify', {
      detail: {
        message: '视频下载已开始',
        title: '下载成功',
        type: 'success',
        duration: 3000
      }
    }));
  } catch (error: any) {
    console.error('Download error:', error);
    window.dispatchEvent(new CustomEvent('notify', {
      detail: {
        message: error.message || '视频下载失败，请稍后重试',
        title: '下载失败',
        type: 'error',
        duration: 5000
      }
    }));
  } finally {
    isDownloading.value = false;
  }
};
</script>

<template>
  <div class="export-actions">
    <div class="tooltip-wrapper">
      <button
        class="btn-action-outline primary"
        @click="exportToNotion"
        :disabled="!takeaways.length || isExportingToNotion"
      >
        <Loader2 v-if="isExportingToNotion" :size="14" class="spin" />
        <ExternalLink v-else :size="14" />
        <span>Notion</span>
      </button>
      <div class="custom-tooltip">直接导出到 Notion 数据库 (需配置 API Key)</div>
    </div>

    <div class="tooltip-wrapper">
      <button
        class="btn-action-outline"
        @click="exportAsMarkdown"
        :disabled="!takeaways.length"
      >
        <Share2 :size="14" />
        <span>复制</span>
      </button>
      <div class="custom-tooltip">复制 Markdown 笔记到剪贴板，支持 手动粘贴</div>
    </div>

    <div class="tooltip-wrapper">
      <button
        class="btn-action-outline"
        @click="downloadFullVideo"
        :disabled="isDownloading"
      >
        <Loader2 v-if="isDownloading" :size="14" class="spin" />
        <Download v-else :size="14" />
        <span>下载</span>
      </button>
      <div class="custom-tooltip">直接下载该视频的完整 MP4 文件</div>
    </div>

    <div class="tooltip-wrapper">
      <button
        class="btn-action-outline"
        @click="generateEditingScript"
        :disabled="!takeaways.length"
      >
        <Scissors :size="14" />
        <span>剪辑</span>
      </button>
      <div class="custom-tooltip">复制剪辑脚本与 FFMPEG 指令到剪贴板</div>
    </div>
  </div>
</template>

<style scoped>
.export-actions {
  display: flex;
  align-items: center;
  gap: 10px;
}

.btn-action-outline {
  display: flex;
  align-items: center;
  gap: 6px;
  background: rgba(255, 255, 255, 0.03);
  border: 1px solid rgba(255, 255, 255, 0.1);
  border-radius: 8px;
  color: var(--text-secondary);
  font-size: 0.85rem;
  font-weight: 600;
  padding: 6px 12px;
  transition: all 0.2s ease;
  cursor: pointer;
  white-space: nowrap;
}

.btn-action-outline:hover:not(:disabled) {
  background: rgba(255, 255, 255, 0.08);
  border-color: rgba(255, 255, 255, 0.2);
  color: var(--text-primary);
  transform: translateY(-1px);
}

.btn-action-outline.primary {
  background: rgba(99, 102, 241, 0.05);
  border-color: rgba(99, 102, 241, 0.15);
  color: var(--text-accent);
}

.btn-action-outline.primary:hover:not(:disabled) {
  background: rgba(99, 102, 241, 0.1);
  border-color: var(--accent-color);
}

.btn-action-outline:disabled {
  opacity: 0.5;
  cursor: not-allowed;
  filter: grayscale(0.6);
}

.btn-action-outline span {
  font-size: 0.85rem;
}

/* Custom Tooltip Styles */
.tooltip-wrapper {
  position: relative;
  display: inline-block;
}

.custom-tooltip {
  position: absolute;
  bottom: 100%;
  left: 50%;
  transform: translateX(-50%) translateY(-8px);
  background: #1e293b;
  color: #f8fafc;
  padding: 8px 12px;
  border-radius: 6px;
  font-size: 0.75rem;
  font-weight: 500;
  line-height: 1.4;
  white-space: nowrap;
  pointer-events: none;
  opacity: 0;
  visibility: hidden;
  transition: all 0.2s cubic-bezier(0.4, 0, 0.2, 1);
  box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.3);
  border: 1px solid rgba(255, 255, 255, 0.1);
  z-index: 9999;
}

.custom-tooltip::after {
  content: '';
  position: absolute;
  top: 100%;
  left: 50%;
  transform: translateX(-50%);
  border-width: 5px;
  border-style: solid;
  border-color: #1e293b transparent transparent transparent;
}

.tooltip-wrapper:hover .custom-tooltip {
  opacity: 1;
  visibility: visible;
  transform: translateX(-50%) translateY(-12px);
}

.btn-action-outline:disabled + .custom-tooltip {
  display: none;
}
</style>
